In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
dataset = pd.read_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/Dataset.csv")
dataset.head()

Channel_of_Recruitment                               Division  \
0  Direct Internal process         Commercial Sales and Marketing   
1        Agency and others  Customer Support and Field Operations   
2  Direct Internal process         Commercial Sales and Marketing   
3        Agency and others         Commercial Sales and Marketing   
4  Direct Internal process               Information and Strategy   

  Foreign_schooled  Gender  Last_performance_score Marital_Status  \
0               No  Female                    12.5        Married   
1              Yes    Male                    12.5        Married   
2              Yes    Male                     7.5        Married   
3              Yes    Male                     2.5         Single   
4              Yes    Male                     7.5        Married   

  No_of_previous_employers Past_Disciplinary_Action  Previous_Award  \
0                        0                       No               0   
1                        0                       No               0   
2                        0                       No               0   
3                        1                       No               0   
4                        1                       No               0   

  Previous_IntraDepartmental_Movement  Promoted_or_Not        Qualification  \
0                                  No              0.0     MSc, MBA and PhD   
1                                  No              0.0  First Degree or HND   
2                                  No              0.0  First Degree or HND   
3                                  No              0.0  First Degree or HND   
4                                  No              0.0  First Degree or HND   

  State_Of_Origin  Targets_met  Training_score_average  Trainings_Attended  \
0         ANAMBRA            1                      41                   2   
1         ANAMBRA            0                      52                   2   
2         KATSINA            0                      42                   2   
3           NIGER            0                      42                   3   
4       AKWA IBOM            0                      77                   3   

   Year_of_birth  Year_of_recruitment  
0           1986                 2011  
1           1991                 2015  
2           1987                 2012  
3           1982                 2009  
4           1990                 2012

In [3]:
dataset.fillna(0, inplace=True)

In [4]:
dataset.isnull().sum()

Channel_of_Recruitment                 0
Division                               0
Foreign_schooled                       0
Gender                                 0
Last_performance_score                 0
Marital_Status                         0
No_of_previous_employers               0
Past_Disciplinary_Action               0
Previous_Award                         0
Previous_IntraDepartmental_Movement    0
Promoted_or_Not                        0
Qualification                          0
State_Of_Origin                        0
Targets_met                            0
Training_score_average                 0
Trainings_Attended                     0
Year_of_birth                          0
Year_of_recruitment                    0
dtype: int64

In [5]:
y = dataset.iloc[:, [10]].values

In [6]:
y[:3]

array([[0.],
       [0.],
       [0.]])

In [7]:
dataset.drop('Promoted_or_Not', axis = 1, inplace = True)

In [8]:
dataset.head()

Channel_of_Recruitment                               Division  \
0  Direct Internal process         Commercial Sales and Marketing   
1        Agency and others  Customer Support and Field Operations   
2  Direct Internal process         Commercial Sales and Marketing   
3        Agency and others         Commercial Sales and Marketing   
4  Direct Internal process               Information and Strategy   

  Foreign_schooled  Gender  Last_performance_score Marital_Status  \
0               No  Female                    12.5        Married   
1              Yes    Male                    12.5        Married   
2              Yes    Male                     7.5        Married   
3              Yes    Male                     2.5         Single   
4              Yes    Male                     7.5        Married   

  No_of_previous_employers Past_Disciplinary_Action  Previous_Award  \
0                        0                       No               0   
1                        0                       No               0   
2                        0                       No               0   
3                        1                       No               0   
4                        1                       No               0   

  Previous_IntraDepartmental_Movement        Qualification State_Of_Origin  \
0                                  No     MSc, MBA and PhD         ANAMBRA   
1                                  No  First Degree or HND         ANAMBRA   
2                                  No  First Degree or HND         KATSINA   
3                                  No  First Degree or HND           NIGER   
4                                  No  First Degree or HND       AKWA IBOM   

   Targets_met  Training_score_average  Trainings_Attended  Year_of_birth  \
0            1                      41                   2           1986   
1            0                      52                   2           1991   
2            0                      42                   2           1987   
3            0                      42                   3           1982   
4            0                      77                   3           1990   

   Year_of_recruitment  
0                 2011  
1                 2015  
2                 2012  
3                 2009  
4                 2012

In [9]:
x = dataset

In [10]:
label1 = ['Channel_of_Recruitment', 'Foreign_schooled', 'Gender', 'Marital_Status']

In [11]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

for cat in label1:
    lb.fit(x[cat])
    x[cat] = lb.transform(x[cat])

In [12]:
x[:3]

Channel_of_Recruitment                               Division  \
0                       1         Commercial Sales and Marketing   
1                       0  Customer Support and Field Operations   
2                       1         Commercial Sales and Marketing   

   Foreign_schooled  Gender  Last_performance_score  Marital_Status  \
0                 0       0                    12.5               0   
1                 1       1                    12.5               0   
2                 1       1                     7.5               0   

  No_of_previous_employers Past_Disciplinary_Action  Previous_Award  \
0                        0                       No               0   
1                        0                       No               0   
2                        0                       No               0   

  Previous_IntraDepartmental_Movement        Qualification State_Of_Origin  \
0                                  No     MSc, MBA and PhD         ANAMBRA   
1                                  No  First Degree or HND         ANAMBRA   
2                                  No  First Degree or HND         KATSINA   

   Targets_met  Training_score_average  Trainings_Attended  Year_of_birth  \
0            1                      41                   2           1986   
1            0                      52                   2           1991   
2            0                      42                   2           1987   

   Year_of_recruitment  
0                 2011  
1                 2015  
2                 2012

In [13]:
label = ['Division', 'Past_Disciplinary_Action', 'Previous_IntraDepartmental_Movement']

In [14]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

for cat in label:
    lb.fit(x[cat])
    x[cat] = lb.transform(x[cat])

In [15]:
x[:3]

Channel_of_Recruitment  Division  Foreign_schooled  Gender  \
0                       1         1                 0       0   
1                       0         2                 1       1   
2                       1         1                 1       1   

   Last_performance_score  Marital_Status No_of_previous_employers  \
0                    12.5               0                        0   
1                    12.5               0                        0   
2                     7.5               0                        0   

   Past_Disciplinary_Action  Previous_Award  \
0                         0               0   
1                         0               0   
2                         0               0   

   Previous_IntraDepartmental_Movement        Qualification State_Of_Origin  \
0                                    0     MSc, MBA and PhD         ANAMBRA   
1                                    0  First Degree or HND         ANAMBRA   
2                                    0  First Degree or HND         KATSINA   

   Targets_met  Training_score_average  Trainings_Attended  Year_of_birth  \
0            1                      41                   2           1986   
1            0                      52                   2           1991   
2            0                      42                   2           1987   

   Year_of_recruitment  
0                 2011  
1                 2015  
2                 2012

In [16]:
label2 = ['State_Of_Origin']

In [17]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

for cat in label2:
    lb.fit(x[cat])
    x[cat] = lb.transform(x[cat])

In [18]:
x[:3]

Channel_of_Recruitment  Division  Foreign_schooled  Gender  \
0                       1         1                 0       0   
1                       0         2                 1       1   
2                       1         1                 1       1   

   Last_performance_score  Marital_Status No_of_previous_employers  \
0                    12.5               0                        0   
1                    12.5               0                        0   
2                     7.5               0                        0   

   Past_Disciplinary_Action  Previous_Award  \
0                         0               0   
1                         0               0   
2                         0               0   

   Previous_IntraDepartmental_Movement        Qualification  State_Of_Origin  \
0                                    0     MSc, MBA and PhD                3   
1                                    0  First Degree or HND                3   
2                                    0  First Degree or HND               20   

   Targets_met  Training_score_average  Trainings_Attended  Year_of_birth  \
0            1                      41                   2           1986   
1            0                      52                   2           1991   
2            0                      42                   2           1987   

   Year_of_recruitment  
0                 2011  
1                 2015  
2                 2012

In [19]:
label3 = ['Channel_of_Recruitment', 'Division', 'Foreign_schooled', 'Past_Disciplinary_Action', 'State_Of_Origin']

In [20]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

for cat in label3:
    lb.fit(x[cat])
    x[cat] = lb.transform(x[cat])

In [21]:
x[:2]

Channel_of_Recruitment  Division  Foreign_schooled  Gender  \
0                       1         1                 0       0   
1                       0         2                 1       1   

   Last_performance_score  Marital_Status No_of_previous_employers  \
0                    12.5               0                        0   
1                    12.5               0                        0   

   Past_Disciplinary_Action  Previous_Award  \
0                         0               0   
1                         0               0   

   Previous_IntraDepartmental_Movement        Qualification  State_Of_Origin  \
0                                    0     MSc, MBA and PhD                3   
1                                    0  First Degree or HND                3   

   Targets_met  Training_score_average  Trainings_Attended  Year_of_birth  \
0            1                      41                   2           1986   
1            0                      52                   2           1991   

   Year_of_recruitment  
0                 2011  
1                 2015

In [22]:
label4 = ['Previous_IntraDepartmental_Movement']

In [23]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

for cat in label4:
    lb.fit(x[cat])
    x[cat] = lb.transform(x[cat])

In [51]:
z = x.Qualification.replace('MSc, MBA and PhD', 'MSc MBA and PhD')

In [25]:
z[:3]

0        MSc MBA and PhD
1    First Degree or HND
2    First Degree or HND
Name: Qualification, dtype: object

In [26]:
z = z.replace('MSc MBA and PhD', 1)
z = z.replace('First Degree or HND', 2)
z = z.replace('Non-University Education', 3)
z[:10]

0    1
1    2
2    2
3    2
4    2
5    2
6    1
7    2
8    1
9    2
Name: Qualification, dtype: object

In [27]:
z.fillna(0, inplace = True)

In [28]:
z.isnull().sum()

0

In [29]:
x.drop('Qualification', axis = 1, inplace = True)

In [30]:
x[:3]

Channel_of_Recruitment  Division  Foreign_schooled  Gender  \
0                       1         1                 0       0   
1                       0         2                 1       1   
2                       1         1                 1       1   

   Last_performance_score  Marital_Status No_of_previous_employers  \
0                    12.5               0                        0   
1                    12.5               0                        0   
2                     7.5               0                        0   

   Past_Disciplinary_Action  Previous_Award  \
0                         0               0   
1                         0               0   
2                         0               0   

   Previous_IntraDepartmental_Movement  State_Of_Origin  Targets_met  \
0                                    0                3            1   
1                                    0                3            0   
2                                    0               20            0   

   Training_score_average  Trainings_Attended  Year_of_birth  \
0                      41                   2           1986   
1                      52                   2           1991   
2                      42                   2           1987   

   Year_of_recruitment  
0                 2011  
1                 2015  
2                 2012

In [31]:
x = x.join(z)

In [32]:
x[:3]

Channel_of_Recruitment  Division  Foreign_schooled  Gender  \
0                       1         1                 0       0   
1                       0         2                 1       1   
2                       1         1                 1       1   

   Last_performance_score  Marital_Status No_of_previous_employers  \
0                    12.5               0                        0   
1                    12.5               0                        0   
2                     7.5               0                        0   

   Past_Disciplinary_Action  Previous_Award  \
0                         0               0   
1                         0               0   
2                         0               0   

   Previous_IntraDepartmental_Movement  State_Of_Origin  Targets_met  \
0                                    0                3            1   
1                                    0                3            0   
2                                    0               20            0   

   Training_score_average  Trainings_Attended  Year_of_birth  \
0                      41                   2           1986   
1                      52                   2           1991   
2                      42                   2           1987   

   Year_of_recruitment Qualification  
0                 2011             1  
1                 2015             2  
2                 2012             2

In [33]:
w = x.No_of_previous_employers.replace('More than 5', 6)

In [34]:
w[:4]

0    0
1    0
2    0
3    1
Name: No_of_previous_employers, dtype: object

In [35]:
x.drop('No_of_previous_employers', axis = 1, inplace = True)

In [36]:
x = x.join(w)

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0) 

In [38]:
x_train

Channel_of_Recruitment  Division  Foreign_schooled  Gender  \
33286                       0         2                 1       0   
3688                        0         4                 1       1   
48982                       0         2                 0       0   
3014                        0         4                 1       0   
35788                       0         1                 1       1   
...                       ...       ...               ...     ...   
45891                       0         2                 1       0   
52416                       0         5                 1       0   
42613                       1         1                 1       1   
43567                       0         1                 1       1   
2732                        1         4                 1       0   

       Last_performance_score  Marital_Status  Past_Disciplinary_Action  \
33286                    10.0               0                         0   
3688                     12.5               0                         0   
48982                     5.0               2                         0   
3014                      7.5               0                         0   
35788                     0.0               0                         0   
...                       ...             ...                       ...   
45891                     7.5               0                         0   
52416                     7.5               0                         0   
42613                    12.5               0                         0   
43567                    12.5               0                         0   
2732                     12.5               2                         0   

       Previous_Award  Previous_IntraDepartmental_Movement  State_Of_Origin  \
33286               0                                    0               30   
3688                0                                    0               11   
48982               0                                    0               11   
3014                0                                    0                7   
35788               0                                    0                0   
...               ...                                  ...              ...   
45891               0                                    1               30   
52416               0                                    0               20   
42613               0                                    0               27   
43567               0                                    0               13   
2732                0                                    0               30   

       Targets_met  Training_score_average  Trainings_Attended  Year_of_birth  \
33286            0                      48                   2           1994   
3688             1                      78                   2           1992   
48982            0                      48                   2           1991   
3014             0                      75                   2           1991   
35788            0                      40                   2           1997   
...            ...                     ...                 ...            ...   
45891            1                      52                   2           1987   
52416            0                      44                   2           1992   
42613            0                      49                   2           1985   
43567            1                      44                   2           1969   
2732             1                      79                   3           1996   

       Year_of_recruitment Qualification No_of_previous_employers  
33286                 2017             2                        1  
3688                  2014             2                        4  
48982                 2014             2                        5  
3014                  2015             2                        1  
35788          

In [39]:
z.unique()

array([1, 2, '0', 3], dtype=object)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
#x_train = sc.fit_transform(x_train)
#x_test = sc.transform(x_test)

In [42]:
x[:4]
#x_test[:4]

array([[ 0.99204546, -0.82994916, -3.2549453 , -1.53622276,  1.28387791,
        -0.47855998, -0.0649165 , -0.15401776, -0.32186682, -1.67912845,
         1.35687789, -1.07593145, -0.41527615, -0.02541857, -0.50045956,
        -1.11679435, -0.83976993],
       [-0.86340183, -0.41631417,  0.30722482,  0.65094726,  1.28387791,
        -0.47855998, -0.0649165 , -0.15401776, -0.32186682, -1.67912845,
        -0.73698599, -0.25328242, -0.41527615,  0.62692311,  0.43739464,
         0.58962507, -0.83976993],
       [ 0.99204546, -0.82994916,  0.30722482,  0.65094726, -0.05262314,
        -0.47855998, -0.0649165 , -0.15401776, -0.32186682,  0.09367708,
        -0.73698599, -1.00114517, -0.41527615,  0.10504977, -0.26599601,
         0.58962507, -0.83976993],
       [-0.86340183, -0.82994916,  0.30722482,  0.65094726, -1.3891242 ,
         2.12222487, -0.0649165 , -0.15401776, -0.32186682,  0.71937315,
        -0.73698599, -1.00114517,  1.22606339, -0.54729191, -0.96938666,
         0.58962507

In [43]:
y[:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [40]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x, y)
#reg.fit(x_train, y_train)

LinearRegression()

In [43]:
#import tensorflow as tf

In [44]:
'''ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))'''

"ann = tf.keras.models.Sequential()\nann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))\nann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))\nann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))"

In [220]:
#ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [221]:
#ann.fit(x_train, y_train, batch_size = 32, epochs = 25)

In [45]:
#y_pred = ann.predict(x_test)
pred = reg.predict(x_test)
#pred = (pred > 0.5)

In [46]:
cf = (np.concatenate((pred.reshape(len(pred),1), y.reshape(len(y),1)),1))
cf[:5]

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10962 and the array at index 1 has size 54808

In [47]:
df = pd.DataFrame(pred.flatten())

In [48]:
df

0
0      0.093450
1     -0.013239
2      0.032672
3      0.019791
4     -0.004088
...         ...
10957  0.101728
10958  0.117886
10959  0.087664
10960  0.102934
10961 -0.002167

[10962 rows x 1 columns]

In [108]:
cf.to_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/Dataset1.csv", index = None)

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'

In [53]:
cf.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [135]:
df = pd.DataFrame(pred.flatten())
#y.flatten(), 

df = df.replace(False, 0)
df = df.replace(True, 1)

In [163]:
df[:50]

0
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  0
11  0
12  0
13  0
14  0
15  0
16  0
17  0
18  0
19  0
20  0
21  0
22  0
23  0
24  0
25  0
26  0
27  0
28  0
29  0
30  0
31  0
32  0
33  0
34  0
35  0
36  0
37  0
38  0
39  0
40  0
41  0
42  0
43  0
44  0
45  0
46  0
47  0
48  0
49  0

In [138]:
df.to_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/Dataset1.csv", index = None)

In [161]:
reg.predict(sc.transform([[0, 3, 1, 1, 127.5, 0, 1, 1, 0, 0, 14, 0, 65, 2, 1976, 2017, 2]]))
#ann.predict(sc.transform([[0, 3, 1, 1, 7.5, 0, 1, 0, 0, 0, 14, 0, 65, 2, 1976, 2017, 2]])) > 0.5

array([[-11.13045839]])

In [159]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y, pred)
print(cm)
accuracy_score(y, pred)

[[51567     0]
 [ 3241     0]]


0.9408662968909648

In [97]:
dataset.head()

Channel_of_Recruitment                               Division  \
0  Direct Internal process         Commercial Sales and Marketing   
1        Agency and others  Customer Support and Field Operations   
2  Direct Internal process         Commercial Sales and Marketing   
3        Agency and others         Commercial Sales and Marketing   
4  Direct Internal process               Information and Strategy   

  Foreign_schooled  Gender  Last_performance_score Marital_Status  \
0               No  Female                    12.5        Married   
1              Yes    Male                    12.5        Married   
2              Yes    Male                     7.5        Married   
3              Yes    Male                     2.5         Single   
4              Yes    Male                     7.5        Married   

  No_of_previous_employers Past_Disciplinary_Action  Previous_Award  \
0                        0                       No               0   
1                        0                       No               0   
2                        0                       No               0   
3                        1                       No               0   
4                        1                       No               0   

  Previous_IntraDepartmental_Movement  Promoted_or_Not        Qualification  \
0                                  No              0.0     MSc, MBA and PhD   
1                                  No              0.0  First Degree or HND   
2                                  No              0.0  First Degree or HND   
3                                  No              0.0  First Degree or HND   
4                                  No              0.0  First Degree or HND   

  State_Of_Origin  Targets_met  Training_score_average  Trainings_Attended  \
0         ANAMBRA            1                      41                   2   
1         ANAMBRA            0                      52                   2   
2         KATSINA            0                      42                   2   
3           NIGER            0                      42                   3   
4       AKWA IBOM            0                      77                   3   

   Year_of_birth  Year_of_recruitment  
0           1986                 2011  
1           1991                 2015  
2           1987                 2012  
3           1982                 2009  
4           1990                 2012

In [98]:
dataset.to_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/Dataset.csv", index = None)

In [103]:
'''#pred = model.predict(X_test)
pred = pd.DataFrame(pred,columns=['Predicted Model'])
sub = pd.concat([test_data.id,pred],axis=1)
#sub.set_index('id',inplace=True).
#sub.to_csv(f"Submission_file_oct-2021.csv")'''

submission = pd.DataFrame(dataset), 'id', "Predicted Model", pred

csv.to_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/submission.csv", index=False)

NameError: name 'csv' is not defined

In [49]:
dataset["prediction"] = cf

csv = df[[0,"prediction"]]

csv.to_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/submission2.csv", index = None)

NameError: name 'cf' is not defined

In [232]:
dataset["prediction"] = [x[0] for x in reg['predictions'][0]['values']]

dataset.to_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/submission1.csv", index = False)

TypeError: 'LinearRegression' object is not subscriptable

In [ ]:
submission = pd.DataFrame('id': pd.read_csv("your test file name")[index], "your target column name": y_pred)

In [ ]:
db["target"] = result //result is your predicted array, db is dataset

to_submit = db[['id',"target"]]

to_submit.to_csv("submission.csv", index = False)

In [139]:
dataset1 = pd.read_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/Dataset1.csv")

In [149]:
dataset1.columns = ['Predicted Values']

In [152]:
dataset1.column

Index(['Predicted Values'], dtype='object')

In [153]:
dataset1.head()

Predicted Values
0                 0
1                 0
2                 0
3                 0
4                 0

In [154]:
dataset1.to_csv("C:/Users/Christopher Ogbeide/Desktop/PROJECT/Dataset2.csv", index = None)

In [ ]:
dataset1.rename(column