In [2]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(3,)


In [5]:
print(arr1[2])

3


In [6]:
arr1[2]

3

In [7]:
arr1[1]=9
print(arr1)

[1 9 3]


In [9]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2[0][2]

3

In [11]:
arr2[1][1]

5

In [12]:
arr2[1]

array([4, 5, 6])

In [14]:
arr2.shape

(2, 3)

In [17]:
arr2[1,-3]

4

In [18]:
arr2[1,0]

4

In [19]:
arrS = np.array(['China', 'India', 'USA', 'Mexico'])
arrS


array(['China', 'India', 'USA', 'Mexico'], dtype='<U6')

In [20]:
arrS.shape

(4,)

In [21]:
arrR = np.arange(0,20,2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
arrL = np.linspace(0,10,20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [33]:
arr = np.random.rand(10)
arr

array([0.72451378, 0.63919827, 0.74856183, 0.30016933, 0.07241111,
       0.41884903, 0.86442426, 0.62736358, 0.1597405 , 0.50711838])

In [34]:
arr = np.random.rand(3,4)
arr

array([[0.94773619, 0.49585606, 0.03842126, 0.63239227],
       [0.60915677, 0.93674901, 0.78617804, 0.71396345],
       [0.63048268, 0.57852512, 0.33899204, 0.86721159]])

In [37]:
print(np.zeros(10))
pri

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
print(np.zeros(10))
print('/n')
print(np.ones((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
print(np.ones((3,10,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [50]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
arr = [0, 1, 2]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [53]:
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [57]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [68]:
arr = np.random.rand(5,3)
arr

array([[0.69539806, 0.27907658, 0.65029088],
       [0.89774458, 0.27931725, 0.91957534],
       [0.03729203, 0.88991515, 0.50889424],
       [0.43168732, 0.81252391, 0.23901302],
       [0.30428449, 0.7623279 , 0.47862851]])

In [69]:
np.diag(arr)

array([0.69539806, 0.27931725, 0.50889424])

In [70]:
arr.ndim

2

In [71]:
arr.size

15

In [73]:
np.random.randint(-10, 10, 4)

array([ 9, -5, -5, -3])

In [74]:
arr+10

array([[10.69539806, 10.27907658, 10.65029088],
       [10.89774458, 10.27931725, 10.91957534],
       [10.03729203, 10.88991515, 10.50889424],
       [10.43168732, 10.81252391, 10.23901302],
       [10.30428449, 10.7623279 , 10.47862851]])

In [75]:
np.exp(arr)

array([[2.00450684, 1.32190857, 1.91609811],
       [2.45406193, 1.32222675, 2.50822502],
       [1.03799611, 2.43492303, 1.66345079],
       [1.53985356, 2.25358867, 1.26999507],
       [1.35565468, 2.14325972, 1.61385949]])

In [76]:
np.sum(arr)

8.185969267647478

In [77]:
np.sum(arr, axis=1)

array([1.62476553, 2.09663717, 1.43610142, 1.48322425, 1.54524091])

In [81]:
np.min(arr, axis=0)

array([0.03729203, 0.27907658, 0.23901302])

In [82]:
arr

array([[0.69539806, 0.27907658, 0.65029088],
       [0.89774458, 0.27931725, 0.91957534],
       [0.03729203, 0.88991515, 0.50889424],
       [0.43168732, 0.81252391, 0.23901302],
       [0.30428449, 0.7623279 , 0.47862851]])

In [83]:
np.sort(arr)

array([[0.27907658, 0.65029088, 0.69539806],
       [0.27931725, 0.89774458, 0.91957534],
       [0.03729203, 0.50889424, 0.88991515],
       [0.23901302, 0.43168732, 0.81252391],
       [0.30428449, 0.47862851, 0.7623279 ]])

In [86]:
arr[:2,:]

array([[0.69539806, 0.27907658, 0.65029088],
       [0.89774458, 0.27931725, 0.91957534]])

In [87]:
arr[:2,:].T

array([[0.69539806, 0.89774458],
       [0.27907658, 0.27931725],
       [0.65029088, 0.91957534]])

In [89]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [90]:
arr1 = np.append(arr,9)
arr1

array([4, 5, 6, 7, 8, 9])

In [91]:
arr2 = np.insert(arr, 0, [1,2,3])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
arr1 = np.array([[1,2,3,4],[1,2,3,4]])
arr2 = np.array([[5,6,7,8],[5,6,7,8]])
arr_cat = np.concatenate((arr1,arr2), axis=0)
print(arr_cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [96]:
cat V= np.vstack((arr1, arr2))
catV

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [97]:
cat = np.hstack((arr1, arr2))
cat

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [98]:
arr = np.array([1,2,3,4,5,6,1,2,4])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [99]:
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 1 2 1 1]


In [102]:
#intersection, differentiation, neither
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1, arr2))


[3 4 5]


In [105]:
#intersection, differentiation, neither
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1, arr2))
print(np.union1d(arr1, arr2))
print(np.setdiff1d(arr1, arr2))
print(np.setxor1d(arr1, arr2)) 

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]


In [2]:
#package for data analyts
import numpy as np
import pandas as pd

from sklearn import svm

#visual your data
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
recipes = pd.read_csv('nn play.csv