In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [81]:
dataset = pd.read_csv('C:/Users/Christopher Ogbeide/Desktop/data/Churn_Modelling.csv')

In [82]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [83]:
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [84]:
x[:4]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63]],
      dtype=object)

In [85]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [86]:
x[:4]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63]], dtype=object)

In [87]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [88]:
x[:4]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63]],
      dtype=object)

In [89]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [90]:
x_train[:4]

array([[0.0, 0.0, 1.0, 667, 0, 34, 5, 0.0, 2, 1, 0, 163830.64],
       [0.0, 1.0, 0.0, 427, 1, 42, 1, 75681.52, 1, 1, 1, 57098.0],
       [1.0, 0.0, 0.0, 535, 0, 29, 2, 112367.34, 1, 1, 0, 185630.76],
       [0.0, 0.0, 1.0, 654, 1, 40, 5, 105683.63, 1, 1, 0, 173617.09]],
      dtype=object)

In [91]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [92]:
x_train[:4]

array([[-1.01460667, -0.5698444 ,  1.74309049,  0.16958176, -1.09168714,
        -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, -2.30455945,  0.91601335,
         0.30102557, -1.37744033, -0.00631193, -0.92159124,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, -1.19119591, -1.09168714,
        -0.94312892, -1.031415  ,  0.57993469, -0.92159124,  0.64259497,
        -1.03227043,  1.48533467],
       [-1.01460667, -0.5698444 ,  1.74309049,  0.03556578,  0.91601335,
         0.10961719,  0.00666099,  0.47312769, -0.92159124,  0.64259497,
        -1.03227043,  1.27652776]])

In [93]:
#Beginning of Artifical Neuron Network 
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [94]:
#Compilinf of ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [95]:
# Training the ANN with Traning Set
ann.fit(x_train, y_train, batch_size = 32, epochs = 40)

Epoch 1/40
250/250 [==============================] - 14s 9ms/step - loss: 0.5827 - accuracy: 0.7649
Epoch 2/40
250/250 [==============================] - 1s 5ms/step - loss: 0.4982 - accuracy: 0.7959
Epoch 3/40
250/250 [==============================] - 1s 5ms/step - loss: 0.4587 - accuracy: 0.7970
Epoch 4/40
250/250 [==============================] - 1s 4ms/step - loss: 0.4378 - accuracy: 0.8000
Epoch 5/40
250/250 [==============================] - 1s 4ms/step - loss: 0.4275 - accuracy: 0.8070
Epoch 6/40
250/250 [==============================] - 1s 4ms/step - loss: 0.4207 - accuracy: 0.8117
Epoch 7/40
250/250 [==============================] - 2s 8ms/step - loss: 0.4129 - accuracy: 0.8191
Epoch 8/40
250/250 [==============================] - 2s 6ms/step - loss: 0.4046 - accuracy: 0.8261
Epoch 9/40
250/250 [==============================] - 1s 5ms/step - loss: 0.3950 - accuracy: 0.8317
Epoch 10/40
250/250 [==============================] - 1s 4ms/step - loss: 0.3853 - accuracy: 0.837

In [100]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5

1/1 [==============================] - 0s 418ms/step


array([[False]])

In [190]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

63/63 [==============================] - 1s 6ms/step


In [185]:
#y_pred = y_pred[:4] > 0.5
#y_pred
#y_pred = y_pred.replace(False, 'Will Stay')
#y_pred = pred.replace(True, 'Will Leave') 

In [192]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [181]:
df = pd.DataFrame(y_pred.flatten(), y_test.flatten()) > 0.5
df = df.replace(False, 'Will Stay')
df = df.replace(True, 'Will Leave')
df[:10]

0
0   Will Stay
1   Will Stay
0   Will Stay
0   Will Stay
0   Will Stay
1  Will Leave
0   Will Stay
0   Will Stay
1   Will Stay
1  Will Leave

In [193]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1504   91]
 [ 196  209]]


0.8565