In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
dataset = pd.read_csv('C:/Users/Christopher Ogbeide/Desktop/data/50_Startups.csv')
dataset[:5]

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [20]:
x = dataset.iloc[:, [0,2]].values
y = dataset.iloc[:, -1].values
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [22]:
print(y_train)

[ 97427.84  81005.76 111313.02  90708.19 122776.86  71498.49  14681.4
 105733.54 110352.25 134307.35  77798.83 125370.37  64926.08 108552.04
 108733.99 166187.94  96778.92 132602.65  99937.59 146121.95 103282.38
  65200.33  96712.8  124266.9  118474.03 107404.34 156122.51 155752.6
  42559.73 191792.06 126992.93 192261.83 129917.04 156991.12 144259.4
 149759.96 152211.77 141585.52  69758.98  89949.14]


In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
#x_train = sc.fit_transform(x_train)
#x_test = sc.transform(x_test)

In [48]:
from sklearn.tree import  DecisionTreeRegressor
regressor =  DecisionTreeRegressor()
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [26]:
regressor.predict([[165000, 435200]])

array([192261.83])

In [27]:
regressor.predict([[125000, 335200]])

array([192261.83])

In [41]:
regressor.predict([[265000, 535200]])

array([192261.83])

In [29]:
'''plt.scatter(x_train, y_train, color = 'green')
plt.plot(x_train, regressor.predict(x_train), color = 'purple')

SyntaxError: unterminated triple-quoted string literal (detected at line 2) (1610345554.py, line 1)

In [49]:
y_pred = regressor.predict(x)

In [53]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [51]:
#df = pd.DataFrame(y_test.flatten(), y_pred.flatten())
#df

In [54]:
df = pd.DataFrame(y_pred.flatten())
df

0
0   192261.83
1   191792.06
2   191792.06
3   166187.94
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   149759.96
9   149759.96
10  146121.95
11  144259.40
12  144259.40
13  144259.40
14  149759.96
15  132602.65
16  126992.93
17  125370.37
18  125370.37
19  122776.86
20  126992.93
21  126992.93
22  111313.02
23  118474.03
24  126992.93
25  107404.34
26  126992.93
27  108733.99
28  103282.38
29  103282.38
30  103282.38
31  103282.38
32  103282.38
33   96712.80
34   96712.80
35   96712.80
36   89949.14
37   96712.80
38   77798.83
39   81005.76
40   81005.76
41   81005.76
42   81005.76
43   69758.98
44   65200.33
45   64926.08
46   77798.83
47   64926.08
48   64926.08
49   69758.98

In [56]:
df.to_csv('C:/Users/Christopher Ogbeide/Desktop/data/Prediction.csv', index = None)

In [57]:
pred = pd.read_csv('C:/Users/Christopher Ogbeide/Desktop/data/Prediction.csv')

In [58]:
pred[:10]

0
0  192261.83
1  191792.06
2  191792.06
3  166187.94
4  166187.94
5  156991.12
6  156122.51
7  155752.60
8  149759.96
9  149759.96

In [59]:
pred.columns = ['Predicted Values']

In [61]:
pred.columns

Index(['Predicted Values'], dtype='object')

In [64]:
pred.head()

Predicted Values
0         192261.83
1         191792.06
2         191792.06
3         166187.94
4         166187.94

In [65]:
dataset2 = dataset.join(pred)

In [66]:
dataset2.head()

R&D Spend  Administration  Marketing Spend       State     Profit  \
0  165349.20       136897.80        471784.10    New York  192261.83   
1  162597.70       151377.59        443898.53  California  191792.06   
2  153441.51       101145.55        407934.54     Florida  191050.39   
3  144372.41       118671.85        383199.62    New York  182901.99   
4  142107.34        91391.77        366168.42     Florida  166187.94   

   Predicted Values  
0         192261.83  
1         191792.06  
2         191792.06  
3         166187.94  
4         166187.94

In [67]:
dataset2.to_csv('C:/Users/Christopher Ogbeide/Desktop/data/New 50_Startups.csv')