In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [3]:
dataset = pd.read_csv('C:/Users/Christopher Ogbeide/Desktop/data/Social_Network_Ads.csv')

In [4]:
dataset[:7]

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0
5   27            58000          0
6   27            84000          0

In [5]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(x[:10])

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]]


In [7]:
print(y[:10])

[0 0 0 0 0 0 0 1 0 0]


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [9]:
x_train[:10]

array([[    29,  28000],
       [    45,  22000],
       [    46, 117000],
       [    32,  18000],
       [    22,  81000],
       [    25,  87000],
       [    48,  33000],
       [    35,  58000],
       [    47,  23000],
       [    26,  32000]], dtype=int64)

In [10]:
print(x_test[:10])

[[    36  33000]
 [    39  61000]
 [    36 118000]
 [    39 122000]
 [    26 118000]
 [    38  65000]
 [    20  36000]
 [    49  89000]
 [    31  18000]
 [    48 141000]]


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
print(x_train[:10])

[[-0.80330081 -1.19121795]
 [ 0.75697997 -1.36859801]
 [ 0.85449752  1.43991958]
 [-0.51074816 -1.48685138]
 [-1.48592365  0.37563923]
 [-1.19337101  0.55301929]
 [ 1.04953262 -1.04340124]
 [-0.21819552 -0.30431766]
 [ 0.95201507 -1.33903467]
 [-1.09585346 -1.07296458]]


In [15]:
print(x_test[:10])

[[-0.12067797 -1.04340124]
 [ 0.17187468 -0.21562763]
 [-0.12067797  1.46948292]
 [ 0.17187468  1.58773629]
 [-1.09585346  1.46948292]
 [ 0.07435713 -0.09737426]
 [-1.68095875 -0.95471121]
 [ 1.14705017  0.61214597]
 [-0.60826571 -1.48685138]
 [ 1.04953262  2.14943981]]


In [18]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p =2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [19]:
y_pred = classifier.predict(x_test)

In [20]:
df = pd.DataFrame(y_test.flatten(), y_pred.flatten())

In [23]:
df[:14]

0
0  0
0  0
1  1
1  1
1  0
0  0
0  0
1  1
0  0
1  0
0  0
0  0
0  0
1  1

In [34]:
print(classifier.predict(sc.transform([[46,117000]])))

[1]


[[40  8]
 [ 3 29]]


0.8625